### PR TITLE
first steps :)

### PR DESCRIPTION
**Pull request by niquola**

### CODE REVIEW

**Comment by yogthos** [comment]
🎉

**Comment by facundoolano** [comment]
This looks great! 

@yogthos how about using [this](https://github.com/macchiato-framework/macchiato-framework.github.io/blob/master/imgs/icon.png) as the github organization profile picture?

**Comment by yogthos** [comment]
that sounds like a plan 👍

**Comment by yogthos** [comment]
I was also thinking it might be good to have the default page in the template use the same style.

**Pull request merged**
